version: '3.8'

services:
  frontend:
    image: ddrenn/nocodb-frontend:20250925
    ports:
      - "5000:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
  backend:
    image: ddrenn/nocodb-backend:20250925
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PORT=3003
      - DB_PATH=/app/data
    volumes:
      # 持久化數據庫文件到單獨目錄
      - ./data:/app/data
    expose:
      - "3003"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  # 數據庫持久化存儲
  db_data:
    driver: local